# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrwsZLqS2Yk8uQCRwnisseVGyJ4Hpyja
"""

# API-key setup — DO NOT hard-code your key in this cell.

import os

# --- Local (with a .env file) ---
# from dotenv import load_dotenv
# load_dotenv()
# API_KEY = os.environ["GROQ_API_KEY"]

# --- Google Colab (Secrets panel) ---
# from google.colab import userdata
# API_KEY = userdata.get("GROQ_API_KEY")

# TODO: set API_KEY using ONE of the methods above.
from google.colab import userdata

API_KEY = userdata.get("GROQ_API_KEY")

if API_KEY is None:
    raise ValueError("GROQ_API_KEY was not found in Colab Secrets.")

print("API key loaded successfully.")

# OpenAI-compatible client (works for Groq and OpenAI; Gemini users see their docs):
from openai import OpenAI

client = OpenAI(
    api_key=API_KEY,
    base_url="https://api.groq.com/openai/v1",   # remove this line if using OpenAI itself
)
MODEL = "llama-3.3-70b-versatile"                # or your provider's model name

print("Client ready.")

# TODO: Write a helper function you will reuse for the WHOLE lab:
#
# def ask_llm(user_prompt, system_prompt="You are a helpful assistant.",
#             temperature=0.7, max_tokens=500):
#     response = client.chat.completions.create(
#         model=MODEL,
#         messages=[
#             {"role": "system", "content": system_prompt},
#             {"role": "user",   "content": user_prompt},
#         ],
#         temperature=temperature,
#         max_tokens=max_tokens,
#     )
#     return response.choices[0].message.content
#
# TODO: Call it once with a simple question and print the answer.
# TODO: Print response.usage as well — how many tokens did your call consume?

def ask_llm(
    user_prompt,
    system_prompt="You are a helpful assistant.",
    temperature=0.7,
    max_tokens=500
):
    response = client.chat.completions.create(
        model=MODEL,
        messages=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
        temperature=temperature,
        max_tokens=max_tokens,
    )

    return response


# Test the function
response = ask_llm("What is a microfinance institution?")

print("Answer:")
print(response.choices[0].message.content)

print("\nToken usage:")
print(response.usage)

"""1.The system role gives the model overall instructions about how it should behave and respond, while the user role contains the specific request or task. For example, a system message could say "You are a helpful financial assistant who gives clear and factual answers," while a user message could ask "What is a microfinance institution?"

2.A token is a small unit of text that an LLM processes. A token can be a whole short word, part of a longer word, punctuation, or another piece of text. API providers bill per token because the amount of text processed and generated affects the computational resources required. Charging based on tokens therefore reflects the amount of work done rather than simply charging the same amount for every API request.
"""

# TODO: Ask the SAME question 5 times at temperature=0.0 and 5 times at temperature=1.2.
#   A good test question: "Suggest a name for a savings product for market traders in Accra."

# TODO: Print all 10 answers, grouped by temperature.

question = "Suggest a name for a savings product for market traders in Accra."

print("===== TEMPERATURE 0.0 =====")

for i in range(5):
    response = ask_llm(
        question,
        temperature=0.0,
        max_tokens=100
    )
    print(f"\nRun {i+1}:")
    print(response.choices[0].message.content)


print("\n\n===== TEMPERATURE 1.2 =====")

for i in range(5):
    response = ask_llm(
        question,
        temperature=1.2,
        max_tokens=100
    )
    print(f"\nRun {i+1}:")
    print(response.choices[0].message.content)

"""At temperature 0.0, the responses were highly consistent across the five runs. The model repeatedly suggested names such as “Makola Save” and “Traders' Treasure”, with only small differences in wording. At temperature 1.2, the responses showed more variation in both the suggested names and the explanations. For example, “Market Booster” and “Sika Box” appeared at the higher temperature, while the lower temperature produced more repetitive responses. For a loan decision-support system, I would use a low temperature such as 0.0 because the system should produce consistent, factual and predictable outputs rather than highly varied responses. Higher temperatures would be more appropriate for creative tasks where generating different ideas is desirable."""

LETTERS = {
"L001": """Dear Sir/Madam,
My name is Akosua Mensah and I have been selling provisions at Makola Market for 12 years.
I am applying for a loan of GHS 8,000 to buy a deep freezer and expand into frozen foods.
My current stall makes about GHS 900 profit each month. I have saved GHS 2,500 with your
susu scheme over the past two years and I have never missed a contribution. I can repay
GHS 450 monthly over 20 months. My sister, a teacher, will stand as my guarantor.
Thank you for considering my application.""",

"L002": """Hello,
I am Kwame Boateng, a commercial driver in Kumasi. I need GHS 25,000 urgently to repair my
trotro engine and settle some personal debts. Business has been slow but it will surely
pick up after the festive season. I can pay back whenever the money comes. I do not have
collateral at the moment but God willing everything will be fine. Please help me quickly.""",

"L003": """Dear Loan Committee,
I am Efua Darko, owner of Darko Fashions, a registered dressmaking business in Takoradi
(registration no. BN-2019-4482). I employ three apprentices. I request GHS 15,000 to
purchase two industrial sewing machines and fabric stock ahead of the Christmas season.
Last year my December revenue alone was GHS 22,000; monthly profit averages GHS 2,800.
I hold a fixed deposit of GHS 5,000 with GCB which I can pledge. Proposed repayment:
GHS 1,100 monthly for 15 months. Attached are my sales records for the past 18 months.""",

"L004": """Good day,
My name is Yaw Owusu. I want a loan for my poultry farm at Nsawam. The amount is GHS 12,000
for feed and 500 new layers. I started the farm last year. Sometimes I make good money,
around GHS 1,500 in a good month, but bird flu affected us in March and I lost many birds.
I am rebuilding now. I can repay in 18 months. My uncle has agreed to guarantee the loan
with his taxi.""",

"L005": """Dear Manager,
I am writing on behalf of the Adenta Women's Weaving Cooperative (14 members). We seek
GHS 30,000 to buy a bulk order of yarn directly from the factory, cutting out middlemen and
raising our margins from 15% to about 35%. The cooperative has operated for 6 years and
holds GHS 9,000 in our group account. We propose repayment of GHS 2,000 monthly over
16 months, backed by our group savings and joint liability agreement.""",

"L006": """Hi,
This is Kofi. I saw your advert. I want GHS 50,000 to start a car washing business, a
provision shop, and also import phones from Dubai. I am 22 and full of energy. I have not
started any of these yet but my friends say I am very business minded. I will pay back in
one year when the businesses are booming. No collateral but I am trustworthy.""",
}

# Gold-standard labels for three letters (for Section 4 evaluation):
GOLD = {
  "L001": {"applicant_name": "Akosua Mensah", "amount_ghs": 8000,  "purpose": "buy deep freezer / expand into frozen foods",
           "monthly_profit_ghs": 900,  "has_collateral_or_guarantor": True,  "repayment_months": 20},
  "L003": {"applicant_name": "Efua Darko",    "amount_ghs": 15000, "purpose": "industrial sewing machines and fabric stock",
           "monthly_profit_ghs": 2800, "has_collateral_or_guarantor": True,  "repayment_months": 15},
  "L006": {"applicant_name": "Kofi",          "amount_ghs": 50000, "purpose": "car wash, provision shop, phone imports",
           "monthly_profit_ghs": None, "has_collateral_or_guarantor": False, "repayment_months": 12},
}

print(f"{len(LETTERS)} letters loaded.")

# TODO: Write SUMMARY_PROMPT_V1 — your first, naive attempt (e.g. just "Summarize this:").
#   Run it on L002 and L006. Read the output critically.

# TODO: Now write SUMMARY_PROMPT_V2 as a proper template with:
#   - a system prompt giving the LLM a ROLE (e.g. "You are an assistant to a microfinance
#     loan officer...") and constraints (factual, neutral, no invented details, 3-4 sentences)
#   - a user prompt template like: f"Summarize this loan application:\n\n{letter_text}"
#   Run V2 on the same two letters at temperature=0.

# TODO: Compare V1 vs V2 outputs side by side. Keep both prompt versions in this notebook.

SUMMARY_PROMPT_V1 = "Summarize this loan application:\n\n{letter_text}"

print("===== L002 — V1 =====")

response_l002_v1 = ask_llm(
    SUMMARY_PROMPT_V1.format(letter_text=LETTERS["L002"]),
    temperature=0.7,
    max_tokens=200
)

print(response_l002_v1.choices[0].message.content)


print("\n===== L006 — V1 =====")

response_l006_v1 = ask_llm(
    SUMMARY_PROMPT_V1.format(letter_text=LETTERS["L006"]),
    temperature=0.7,
    max_tokens=200
)

print(response_l006_v1.choices[0].message.content)

SUMMARY_SYSTEM_V2 = """
You are an assistant to a microfinance loan officer.

Summarize loan application letters into a short, factual and neutral brief.
Use only information explicitly stated in the letter. Do not invent, assume,
or infer information that is not provided. Focus on the applicant, requested
loan amount, purpose of the loan, financial/business information, repayment
proposal, and collateral or guarantor information.

Write exactly 3-4 sentences. Do not make an approval or rejection decision.
"""

SUMMARY_PROMPT_V2 = """
Summarize this loan application for a busy loan officer:

{letter_text}
"""

print("===== L002 — V2 =====")

response_l002_v2 = ask_llm(
    SUMMARY_PROMPT_V2.format(letter_text=LETTERS["L002"]),
    system_prompt=SUMMARY_SYSTEM_V2,
    temperature=0.0,
    max_tokens=200
)

print(response_l002_v2.choices[0].message.content)


print("\n===== L006 — V2 =====")

response_l006_v2 = ask_llm(
    SUMMARY_PROMPT_V2.format(letter_text=LETTERS["L006"]),
    system_prompt=SUMMARY_SYSTEM_V2,
    temperature=0.0,
    max_tokens=200
)

print(response_l006_v2.choices[0].message.content)

"""1.What concrete problems did V1's output have that V2 fixed? V1 produced generally accurate summaries, but it sometimes made assumptions that were not directly stated in the letters. For example, V1 said that Kofi had "no prior experience" in the businesses, even though the letter only states that he had not started them yet. V2 was more careful about distinguishing stated facts from assumptions and explicitly identified missing information, such as the lack of a specific repayment schedule in L002. V2 also gave the summaries a clearer focus on information relevant to a loan officer.

2.Why is "no invented details" an essential instruction in this application? What is this failure mode called in the LLM literature? "No invented details" is essential because a loan officer could make an unfair or incorrect decision if the system adds information that was not provided by the applicant. For example, inventing financial information, collateral, or repayment details could make an applicant appear stronger or weaker than they actually are. This failure mode is called hallucination, where an LLM generates information that is unsupported by the provided source.
"""

# TODO: Write EXTRACT_PROMPT — a template that instructs the model to return ONLY a JSON
#   object with EXACTLY these keys:
#     applicant_name (string), amount_ghs (number), purpose (string),
#     monthly_profit_ghs (number or null), has_collateral_or_guarantor (boolean),
#     repayment_months (number or null)
#   Techniques to use:
#     - explicit schema in the prompt
#     - ONE worked example (few-shot) using a letter you write yourself (not from LETTERS!)
#     - "If a field is not stated in the letter, use null. Do not guess."
#     - temperature=0

# TODO: Write extract_fields(letter_text) that calls the LLM, strips any ```json fences,
#   json.loads() the result, and returns a dict. Handle parse failures gracefully
#   (return None and print a warning).

# TODO: Run it on ALL SIX letters; collect results into a pandas DataFrame (one row per
#   letter) and display it.

EXTRACT_PROMPT = """
You are extracting structured information from a loan application letter.

Return ONLY a valid JSON object with EXACTLY these six keys:

{{
  "applicant_name": "string",
  "amount_ghs": "number",
  "purpose": "string",
  "monthly_profit_ghs": "number or null",
  "has_collateral_or_guarantor": "boolean",
  "repayment_months": "number or null"
}}

Rules:
1. Use only information explicitly stated in the letter.
2. Do not guess, infer, or invent information.
3. If a field is not stated in the letter, use null.
4. amount_ghs, monthly_profit_ghs, and repayment_months must be numbers, not strings.
5. Convert repayment periods stated in years into months. For example, "one year"
   means 12 months and "two years" means 24 months.
6. has_collateral_or_guarantor must be true if the letter explicitly mentions
   collateral or a guarantor, and false if the letter explicitly says there is none.
7. Return ONLY the JSON object. Do not include explanations, markdown, or
   ```json fences.

Here is one example:

LETTER:
Dear Loan Officer,

My name is Abena Owusu and I run Sweet Crumbs Bakery in Accra.
I am requesting GHS 10,000 to purchase a commercial oven and additional baking supplies.
The bakery makes approximately GHS 1,500 profit each month.
I can repay GHS 700 per month for 15 months.
My mother will act as my guarantor.

Thank you.

JSON:
{{
  "applicant_name": "Abena Owusu",
  "amount_ghs": 10000,
  "purpose": "purchase a commercial oven and additional baking supplies",
  "monthly_profit_ghs": 1500,
  "has_collateral_or_guarantor": true,
  "repayment_months": 15
}}

Now extract the information from this loan application:

{letter_text}
"""
import json

def extract_fields(letter_text):
    response = ask_llm(
        EXTRACT_PROMPT.format(letter_text=letter_text),
        temperature=0.0,
        max_tokens=300
    )

    result = response.choices[0].message.content.strip()

    # Remove markdown JSON fences if the model adds them
    if result.startswith("```json"):
        result = result[7:]
    elif result.startswith("```"):
        result = result[3:]

    if result.endswith("```"):
        result = result[:-3]

    result = result.strip()

    try:
        return json.loads(result)
    except json.JSONDecodeError:
        print("Warning: Could not parse model output as JSON.")
        print("Model output:", result)
        return None


test_result = extract_fields(LETTERS["L001"])
print(json.dumps(test_result, indent=2))

import pandas as pd

extracted_results = []

for letter_id, letter_text in LETTERS.items():
    result = extract_fields(letter_text)

    if result is not None:
        result["letter_id"] = letter_id
    else:
        result = {
            "letter_id": letter_id,
            "applicant_name": None,
            "amount_ghs": None,
            "purpose": None,
            "monthly_profit_ghs": None,
            "has_collateral_or_guarantor": None,
            "repayment_months": None
        }

    extracted_results.append(result)

extracted_df = pd.DataFrame(extracted_results)

columns = [
    "letter_id",
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]

extracted_df = extracted_df[columns]

display(extracted_df)

l006_result = extract_fields(LETTERS["L006"])

print(json.dumps(l006_result, indent=2))

"""1.Why must the few-shot example NOT come from the six letters you are processing? The few-shot example should not come from the six letters being processed because it could give the model information about the actual test data and make the extraction evaluation less independent. Using a separate fictional example shows the model the required format and task without giving it the answers to the letters that will later be evaluated.

2.Why "use null, do not guess" — what did the model do without that instruction? "Use null, do not guess" is important because some information is not provided in every application. For example, L002 does not state a monthly profit or a specific repayment period, so those fields should be null rather than invented. Without this instruction, an LLM could try to fill missing information using assumptions, which could introduce inaccurate information into the system.

3.Why is temperature=0 the right choice for extraction but arguably not for creative tasks? Temperature 0 is appropriate for structured extraction because we want the model to produce consistent and predictable results when identifying information from the same letter. For creative tasks, a higher temperature can be useful because it allows more variation and different ideas to be generated.
"""

# TODO: Write BRIEF_PROMPT — it receives the letter AND your extracted JSON, and must output:
#     1. Strengths (bullet points, grounded in the letter)
#     2. Risks / red flags (bullet points)
#     3. Missing information the officer should request
#     4. Suggested next step (e.g. "invite for interview", "request documents",
#        "flag for senior review") — NOT "approve" or "reject".
#   Give the model an explicit instruction that final decisions are made by humans.

# TODO: Generate briefs for ALL SIX letters. Print the briefs for L001, L002, and L006 —
#   three very different applications.

BRIEF_PROMPT = """
You are an assistant supporting a microfinance loan officer.

Prepare a concise, neutral decision-support brief using ONLY information
explicitly stated in the original loan application and the extracted JSON.

IMPORTANT:
- Do not invent, assume, speculate, or infer facts.
- Do not make judgments based on age, gender, location, writing style,
  or other personal characteristics.
- Do not treat an applicant's claims as verified facts. Clearly identify
  them as claims when relevant.
- Do not describe something as "stable", "significant", "high risk",
  "unrealistic", or similar unless the letter itself provides evidence
  supporting that characterization.
- If information is not provided, classify it as MISSING INFORMATION,
  not as a risk.
- Do not introduce generic business risks that are not directly supported
  by the application.
- Do not repeat the same point in multiple sections.
- Do not show your reasoning process or intermediate steps.

Your output MUST contain exactly these four headings and no additional
headings:

## Strengths
- List positive factors explicitly supported by the application.
- Clearly distinguish verified information from claims made by the applicant.

## Risks / Red Flags
- List concerns directly supported by information in the application,
  such as existing business difficulties, lack of collateral, or an
  unclear repayment proposal.
- Do not turn missing information into a risk.

## Missing Information
- List important information that is not provided but would help the loan
  officer assess the application.
- Do not list information that is already stated in the letter.

## Suggested Next Step
- Recommend practical actions such as requesting documents, verifying
  financial information, inviting the applicant for an interview,
  requesting a business plan, or flagging the application for senior review.
- Do NOT recommend "approve" or "reject".
- The final lending decision must always be made by a human loan officer.

Keep the entire brief concise and factual.

Original loan application:
{letter_text}

Extracted information:
{extracted_json}
"""

briefs = {}

for letter_id, letter_text in LETTERS.items():
    extracted = extracted_df[
        extracted_df["letter_id"] == letter_id
    ].iloc[0].to_dict()

    extracted_json = json.dumps(extracted, indent=2)

    response = ask_llm(
        BRIEF_PROMPT.format(
            letter_text=letter_text,
            extracted_json=extracted_json
        ),
        temperature=0.0,
        max_tokens=600
    )

    briefs[letter_id] = response.choices[0].message.content


print("===== L001 =====")
print(briefs["L001"])

print("\n===== L002 =====")
print(briefs["L002"])

print("\n===== L006 =====")
print(briefs["L006"])

print("===== L003 =====")
print(briefs["L003"])

"""1. Compare the briefs for L003 and L006. Did the system identify the right strengths and red flags in each?
The system identified most of the important strengths and red flags in both applications. For L003, it correctly identified the registered business, reported monthly profit, sales records, and fixed deposit that could be pledged as collateral as strengths. It also identified useful missing information such as verification of the financial information and details about the planned expansion. However, it incorrectly described the repayment plan as potentially unrealistic even though the application did not provide enough information to support that judgment. For L006, the system correctly identified the lack of collateral, the fact that none of the proposed businesses had started, and the uncertainty of relying on future business success for repayment. Overall, the system was useful but still required human review because some of its risk assessments could be unsupported.

2. Why did we forbid the model from outputting "approve"/"reject"? Give one practical and one ethical reason.
Practically, the LLM can make mistakes or misunderstand information, so a human loan officer should review the application and verify important information before making the final decision. Ethically, automatically approving or rejecting loans could unfairly deny applicants access to credit because of errors, biased interpretations, or differences in how applicants communicate. Keeping a human decision-maker involved provides an opportunity to identify and correct these problems.

Commit Hash: 0ecf3e42529b4e51bea5700aabbef18d81ddc059
"""

# TODO: For the three letters in GOLD, compare your extracted DataFrame to the gold values
#   field by field. Compute per-field accuracy across the three letters
#   (name matching can be case-insensitive; numbers must match exactly).

# TODO: Display a small table: rows = fields, columns = L001 / L003 / L006 / accuracy.

# Part 4.1 — Extraction accuracy against gold labels

evaluation_rows = []

for field in [
    "applicant_name",
    "amount_ghs",
    "purpose",
    "monthly_profit_ghs",
    "has_collateral_or_guarantor",
    "repayment_months"
]:
    row = {"field": field}

    correct_count = 0

    for letter_id in ["L001", "L003", "L006"]:
        predicted = extracted_df.loc[
            extracted_df["letter_id"] == letter_id, field
        ].iloc[0]

        gold = GOLD[letter_id][field]

        # Name: case-insensitive comparison
        if field == "applicant_name":
            correct = str(predicted).strip().lower() == str(gold).strip().lower()

        # Purpose: compare the important words rather than requiring
        # identical wording.
        elif field == "purpose":
            predicted_text = str(predicted).lower()
            gold_text = str(gold).lower()

            purpose_groups = {
                "L001": ["deep freezer", "frozen foods"],
                "L003": ["sewing machines", "fabric stock"],
                "L006": ["car wash", "provision shop", "phone"]
            }

            correct = all(
                term in predicted_text
                for term in purpose_groups[letter_id]
            )

        # Numbers and booleans must match exactly
        else:
            if pd.isna(gold):
                correct = pd.isna(predicted)
            else:
                correct = predicted == gold

        row[letter_id] = "✓" if correct else "✗"

        if correct:
            correct_count += 1

    row["accuracy"] = f"{correct_count / 3:.0%}"

    evaluation_rows.append(row)

evaluation_df = pd.DataFrame(evaluation_rows)

display(evaluation_df)

"""1. Report your extraction accuracy. Which field was hardest for the model and why?
The extraction system achieved 100% accuracy on all six evaluated fields across L001, L003, and L006. No field was incorrect in the final evaluation. However, repayment months was initially more challenging because L006 stated the repayment period as "one year" rather than explicitly stating 12 months. After adding an instruction to convert years into months, the model correctly extracted it as 12 months. This shows that clear prompt instructions can improve structured extraction.
"""

# TODO: Run extract_fields() on letter L004 FIVE times at temperature=0 and FIVE times at
#   temperature=1.0.

# TODO: For each temperature, report how many of the 5 runs produced (a) valid JSON and
#   (b) identical values across runs. A simple approach: json.dumps(result, sort_keys=True)
#   and count unique strings.

# Part 4.2 — Reliability experiment

import json

reliability_results = {}

for temperature in [0.0, 1.0]:
    runs = []

    print(f"===== Temperature {temperature} =====")

    for i in range(5):
        result = extract_fields(LETTERS["L004"])
        runs.append(result)

        print(f"\nRun {i+1}:")
        print(json.dumps(result, indent=2))

    # Count valid JSON results
    valid_runs = [r for r in runs if r is not None]

    # Convert results to comparable strings
    result_strings = [
        json.dumps(r, sort_keys=True)
        for r in valid_runs
    ]

    unique_results = len(set(result_strings))

    reliability_results[temperature] = {
        "valid_json": len(valid_runs),
        "identical_values": 5 - unique_results if False else (
            5 if unique_results == 1 and len(valid_runs) == 5 else 0
        ),
        "unique_outputs": unique_results
    }

print("\n===== RELIABILITY SUMMARY =====")

for temperature, result in reliability_results.items():
    print(
        f"Temperature {temperature}: "
        f"{result['valid_json']}/5 valid JSON, "
        f"{result['identical_values']}/5 identical across runs"
    )

"""2. What did the reliability experiment show about temperature and production systems?
For L004, all five runs at temperature 0.0 and all five runs at temperature 1.0 produced valid JSON and identical values across the five runs. Therefore, in this particular experiment, increasing the temperature from 0.0 to 1.0 did not reduce the consistency of the structured extraction. However, this was only one letter and five runs per temperature, so it is not enough to conclude that temperature never affects reliability. For a production extraction system, consistent outputs are important, so temperature 0 is still a sensible choice, combined with validation and error handling.
"""

# TODO: Design TWO adversarial tests and run them:
#   Test 1 — Ask your summarizer a question about a detail that is NOT in a letter
#     (e.g. "What is the applicant's credit score?"). Does it admit the information is
#     absent, or does it invent one?
#   Test 2 — Feed your extractor an EMPTY or IRRELEVANT text (e.g. a weather report).
#     Does it return nulls, or does it fabricate an applicant?

# TODO: Record the outputs verbatim below and label each PASS or FAIL.

# Part 4.3 — Hallucination Test 1

hallucination_question = """
What is the applicant's credit score?
If the credit score is not provided in the application, say that it is not provided.
"""

response = ask_llm(
    hallucination_question + "\n\nLoan application:\n" + LETTERS["L002"],
    system_prompt="""
You are an assistant to a microfinance loan officer.
Use only information explicitly stated in the loan application.
Do not invent, assume, or infer missing information.
If information is not provided, clearly say that it is not provided.
""",
    temperature=0.0,
    max_tokens=100
)

test_1_output = response.choices[0].message.content

print("===== HALLUCINATION TEST 1 =====")
print(test_1_output)

# Part 4.3 — Hallucination Test 2

irrelevant_text = """
Today's weather forecast for Accra is sunny with a high of 30 degrees Celsius.
There may be light rain in the evening. Temperatures will remain warm throughout
the week.
"""

test_2_result = extract_fields(irrelevant_text)

print("===== HALLUCINATION TEST 2 =====")
print(json.dumps(test_2_result, indent=2))

"""### Hallucination Test 1 — PASS

Input: Asked the summarizer for the applicant's credit score when no credit score was provided in L002.

Output:
"The applicant's credit score is not provided."

Result: PASS. The model correctly identified that the information was absent instead of inventing a credit score.


### Hallucination Test 2 — PASS

Input: Irrelevant weather report provided to the structured extraction system.

Output:
{
  "applicant_name": null,
  "amount_ghs": null,
  "purpose": null,
  "monthly_profit_ghs": null,
  "has_collateral_or_guarantor": null,
  "repayment_months": null
}

Result: PASS. The extractor returned null for all fields rather than fabricating loan application information.

1. Report your extraction accuracy. Which field was hardest for the model and why?
The extraction system achieved 100% accuracy across all six fields for L001, L003, and L006. No field was incorrect in the final evaluation. Repayment months was initially the most challenging because L006 expressed the repayment period as "one year" rather than directly stating 12 months. After adding an instruction to convert years into months, the model correctly extracted the value as 12.

2. What did the reliability experiment show about temperature and production systems?
For L004, both temperature 0.0 and temperature 1.0 produced valid JSON in all five runs, and all five outputs were identical at each temperature. Therefore, in this experiment, increasing the temperature did not reduce extraction consistency. However, the experiment only used one letter and five runs per temperature, so it is not enough to conclude that temperature never affects reliability. Production systems should use consistent settings together with validation and error handling.

3. Did your system hallucinate under probing? If yes, how could the prompt (or the system design around it) reduce the risk?
No. Both hallucination tests passed. When asked for a credit score that was not provided, the summarizer stated that the information was not provided. When given an irrelevant weather report, the extractor returned null for all fields instead of fabricating information. The system could further reduce hallucination risk by continuing to use explicit instructions to rely only on provided information, return null for missing fields, validate JSON outputs, and keep a human involved in important decisions.

1. Letters L002 and L006 would likely be declined. If the bank fully automated decisions with your system, who could be unfairly harmed, and how?
Applicants who have difficulty writing in English could be unfairly harmed if the system interpreted poor grammar, spelling, or communication style as a sign of poor creditworthiness. This could disadvantage applicants who run successful businesses but have limited English proficiency. Other applicants could also be harmed if the LLM makes an incorrect inference or extracts information incorrectly and that error is used to make a lending decision. Human review is therefore important before any final decision is made.

2. Loan letters contain personal data. What are the implications of sending them to a third-party API in another country? What would you check before deploying this at a real Ghanaian microfinance institution?
Sending loan applications to a third-party API in another country could expose applicants' personal and financial information to an external service and may create privacy, security, data-transfer, and regulatory risks. Before deployment, I would check the API provider's data handling and retention policies, security measures, where the data is stored and processed, whether the provider uses submitted data for model training, and whether the institution's use of the service complies with applicable Ghanaian data-protection requirements and its own privacy policies.

3. Name TWO concrete safeguards you would build around this system in production.
First, human review: The system should only provide summaries, extracted information, and decision-support briefs. A qualified loan officer should review the original application and supporting documents before making the final lending decision.
Second, monitoring and audit logs: The system should record model outputs, extraction errors, and important decisions so that errors and patterns of unfair outcomes can be detected and investigated. There should also be a clear process for applicants to appeal or request human review of a decision.

1. Prompting as engineering: How is iterating on a prompt similar to and different from iterating on the model hyperparameters you tuned in Lab 3?

Iterating on a prompt is similar to tuning model hyperparameters because both involve changing settings, testing the results, and using the results to improve performance. In Lab 3, I changed model hyperparameters such as learning rate or other training settings to improve the neural network. In Lab 4, I changed instructions in the prompt to improve the LLM's behaviour, such as explicitly telling it to use null for missing information and convert years into months. The main difference is that prompt iteration changes the instructions given to an already-trained model, while hyperparameter tuning changes how a model is trained or how it learns from data.

2. Trust: After your Section 4 evaluation, would you trust this system to run unattended? What single evaluation result most influenced your answer?

I would not trust this system to run completely unattended. Although it achieved 100% extraction accuracy on the three gold-labeled letters, produced identical results in all five reliability runs at both temperatures tested, and passed both hallucination tests, the evaluation was still limited. The result that most influenced my answer was the hallucination and decision-support testing because even a system with high extraction accuracy could make an unsupported inference in a loan context. A human loan officer should therefore review the original application and the system's output before any lending decision.

3. Cost and scale: Estimate the tokens needed to process 1,000 applications per month. What does that imply for provider choice?

Your actual Section 2 usage was:

459 total tokens per API call.

So:

459 × 1,000 = 459,000 tokens/month

Answer:

My API call used 48 prompt tokens and 411 completion tokens, for a total of 459 tokens. If one application required approximately the same number of tokens, processing 1,000 applications per month would require approximately 459,000 tokens. This suggests that token usage and pricing should be considered when choosing an API provider. A provider with competitive pricing, reliable performance, and appropriate data-protection policies would be important for a production system. As the number of applications increases, reducing unnecessary prompt and output tokens could also help control costs.

4. Looking back at the course: Why does calling an API beat training your own model — and when would it not?

Calling an API is better for this task because a foundation model is already trained and can understand natural-language loan applications without requiring us to collect and label a large training dataset or train a model ourselves. It is also faster to develop and easier to update by changing prompts. However, training our own model could be preferable if the institution had a large, high-quality dataset, needed very specialized behaviour, required greater control over the model, or had privacy requirements that made sending sensitive loan applications to an external API inappropriate.
"""